enum ActionTypes {
    AUTH_START = "AUTH_START",
    AUTH_SUCCESS = "AUTH_SUCCESS",
    AUTH_FAIL = "AUTH_FAIL",
    AUTH_LOGOUT = "AUTH_LOGOUT",
    SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH",
    AUTH_ACCESS_TOKEN_UPDATES="AUTH_ACCESS_TOKEN_UPDATES",
    AUTH_REFRESH_TOKEN_UPDATES="AUTH_REFRESH_TOKEN_UPDATES",
    AUTH_UPDATE_ACCESS_TOKEN="AUTH_UPDATE_ACCESS_TOKEN"
}

export default ActionTypes;

export interface IAction {
    type:ActionTypes;
}